---
title: "Import Overweight Data"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE,
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

library(tidyverse)
library(ggplot2)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

# Import Data 
Data Source: [NYC Data Portal](https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-explorer/overweight/?id=2061#display=summary) 

  * Data accessed: `11/27/2023` 
  * Full table loaded for "Overweight and Obese Adults"

```{r import_data}
data = read_csv('./data/SDI_data/nyc_overweight_or_obesity_adults.csv') |>
    janitor::clean_names()

tidy_weight =
  data |>
  mutate(number = gsub("\\*", "", number)) |>
  mutate(number = gsub(",", "", number)) |>
  mutate(number = as.numeric(number)) |>
  mutate(
    percent_low = as.numeric(gsub("^.*\\(\\s*", "", gsub("\\s*,.*$", "", percent))),
    percent_high = as.numeric(gsub("^.*\\,\\s*", "", gsub("\\)$", "", percent))),
percent = as.numeric(ifelse(grepl("\\*", percent),
                                gsub("\\*.*$", "", percent),
                                gsub("\\s*\\(.*", "", percent)))) |>
  rename(year = time)
```

# Save
```{r save_clean}
data_2019 = tidy_weight |>
  filter(year == 2019)

write_csv(data_2019, "data/SDI_data/overweight_data_clean.csv")

```






