---
title: "<span style='color: blue;'>About Us</span>"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
css: styles.css
---
 &nbsp;
 
 ***
 
# Laura O'Carroll

Laura is a second year MPH student and a Senior Policy Analyst for the Chicago Department of Public Health. 

[Learn more about Laura](https://github.com/laura0carroll)

 &nbsp;

# Courtney Diamond

Courtney is a third year PhD student in the Department of Biomedical Informatics at Columbia University. 

[Learn more about Courtney](https://courtneyjdiamond.github.io/)

[Linkedin](https://www.linkedin.com/in/courtneyjdiamond/)

 &nbsp;

# Hyun Jin Jung

Hyun Jin is a first-year master’s student in Biostatistics, Clinical Research Methods track.

[Learn more about Hyun](https://github.com/hyun7in)

 &nbsp;

# Jesus Luevano

Jesus is a second year MS POR candidate. He is also a third year Gastroenterology Fellow at Columbia University Medical Center. 

[Learn more about Jesus](https://github.com/jmlue)

[Linkedin](https://www.linkedin.com/in/jesus-m-luevano-md/)

 &nbsp;

# Kayla Schiffer-Kane

Kayla is a PhD student in the Department of Biomedical Informatics. She is in [Dr. Chunhua Weng's lab](https://people.dbmi.columbia.edu/~chw7007/).

 &nbsp;

# Haley Zylberberg

She is a second year MS POR candidate. He is also a third year Gastroenterology Fellow at Columbia University Medical Center. 

[Learn more about Haley](https://haleyzylberberg.github.io/)