---
title: "P8105 Fall 2023 Final Project"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

Citibike Jan/2019 ~ Dec/2019
```{r import citibike, eval = FALSE}
citibike <- 
 tibble(
 files = list.files("citibike/"),
  path = str_c("citibike/", files)
  ) |>
mutate(data = map(path, ~read_csv(.x, col_types = cols(
  'end station id' = col_double(),
   'start station id' = col_double()
  )))) |>
unnest(cols = c(data))
```

Tidy dataset:
 * recode gender
 * filter trip duration to more than 5 minutes but less than 1 day
 * include trips that started in 2018 but ended in 2019 and trips that started in 2019 but ended in 2020
 * create an age variable
 * create a trip duration in minutes variable
 
```{r tiday citibike, eval = FALSE}
citibike_df <- citibike |>
  janitor::clean_names() |>
  select(-files, -path) |>
  rename(trip_duration_sec = tripduration,
         start_time = starttime,
         stop_time = stoptime,
         user_type = usertype)|>
  mutate(gender = recode(gender,
                         "0" = "Unknown",
                         "1" = "Male",
                         "2" = "Female"),
        trip_duration_min = trip_duration_sec / 60,
        age = 2019 - birth_year
        ) |>
  filter(
    trip_duration_sec >= 300,
    trip_duration_sec <= 86400,
    as.Date(stop_time) >= as.Date("2019-01-01"),
    as.Date(start_time) <= as.Date("2019-12-31")
  )  |>
  select(trip_duration_sec, trip_duration_min, everything())

```


Import air quality data 
```{r air quality}
air <- read_csv("air_quality/Air_Quality_20231126.csv") 
```

```{r air quality tidy}
 air_quality_df =air |>
  janitor::clean_names() |>
  mutate(
    start_date = mdy(start_date),
    year = year(start_date)
  ) |>
  filter(year == "2019")
```

SDI Data and tidy
```{r sdi}
SDI_df <- read_csv("SDI_data/rgcsdi-2015-2019-zcta.csv") |>
  janitor::clean_names() |>
  select(zcta5_fips, sdi_score)|>
  rename(zip=zcta5_fips)
```

Import UHF/ZipCode crosswalk (available from `https://www.nyc.gov/assets/doh/downloads/pdf/ah/zipcodetable.pdf`)

```{r}
# install.packages("pdftables")
# install.packages("pdftools")

library(pdftables)
library(pdftools)
library(magrittr)

uhf_zip = 
  pdf_text("data/zipcodetable.pdf") |> 
  extract(1)

uhf_zip_df =
  uhf_zip |> 
  str_split("\n") |>
  tibble() |> 
  rename("data" = "str_split(uhf_zip, \"\\n\")") |> 
  unnest("data") |> 
  filter(data != "") |> 
  filter(!row_number() %in% c(1, 2, 51)) |> 
  filter(!row_number() %in% c(1, 2, 10, 22, 33, 44)) |> 
  mutate(data = str_squish(data)) |> 
  mutate(data = str_remove_all(data, "-")) |> 
  mutate(data = str_squish(data)) |> 
  separate(data, into = c("UHF", "rest"), sep = "(?<=\\d\\s)") |> 
  separate(col = "rest", into = c("neighborhood", "zip"), sep = "(?=\\s\\d)", extra = "merge") |> 
  separate(col = "zip", into = c("zip1", "zip2", "zip3", "zip4", "zip5", "zip6", "zip7", "zip8", "zip9"), sep = ",") |> 
  mutate(across(everything(), ~ str_trim(.x))) |> 
  mutate(across(c("zip1":"zip9"), ~ as.numeric(.x))) |> 
  mutate(UHF = as.numeric(UHF)) |> 
  pivot_longer(c(zip1:zip9), names_to = "zip_name", values_to = "zip") |> 
  filter(!is.na(zip)) |> 
  select(!zip_name)

uhf_zip_df
```

