---
title: "Sources of Data"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
css: styles.css
---

<style>
  h1 {
     font-weight: bold;
  }
</style>


[**CitiBike Data**](https://s3.amazonaws.com/tripdata/index.html) We will use the publicly available CitiBike. These datasets contain monthly logs of trips and record data elements such as the ride ID, the user's status (subscriber or casual user), the trip start location and longitude/latitude coordinates, the trip end location and latitude/longitude coordinates, and the trip start/stop times and duration.

* The available data also vary by year. For example, 2023 contains data on mechanical versus electric break usage and whether the rider was a CitiBike member or not. Pending initial exploration of completion, we will determine feasibility of incorporating these different variables in our analysis. 

[**Air Quality Data**](https://data.cityofnewyork.us/Environment/Air-Quality/c3uy-2p5r) Additionally, we plan to investigate how weather trends impact Citibike ridership in the area using data from NYC Open Data, contributed by the Department of Hygiene and Mental Health. These data include the air quality indexes measured across boroughs in NYC.

[**Social Deprivation Index**](https://www.graham-center.org/maps-data-tools/social-deprivation-index.html) Social deprivation index (SDI) is an effort in generating composite measures of socioeconomic factors across NYC by census tract. We will use these datasets to explore CitiBike availability and usage patterns across neighborhoods.

[**Overweight Data**](https://a816-dohbesp.nyc.gov/IndicatorPublic/Subtopic.aspx?theme_code=2,3&subtopic_id=113) To provide an insight into health outcomes associated with factors such as physical acitvity aand socioeconomic factors, we will use NYC's publicly available overweight health outcomes data, which is.  

[**Weather Data**](https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdc:C00861/html) Lastly, for temperature-related trends, we will use data from the Global Historical Climatology Network - Daily (GHCN-Daily) dataset published by the National Centers for Environmental Information (NCEI). These data reflect those used in the rnoaa package, and include the weather station identifier, the date, latitude/longitude, maximum temperature, minimum temperature, and precipitation. 

