---
title: "From Pedals to Patterns: A P8105 Citibike Data Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
css: styles.css
---

<style>
  h1 {
    text-align: center;
     font-weight: bold;
  }
</style>

```{r library, include=FALSE}
library(tidyverse)
library(shiny)
library(shinyjs)
shinyjs::useShinyjs()
```

***

## Screencast 

<link here to embed video>
  &nbsp;

## Team Members
  - Laura O'Carroll, lgo2107<br>
  - Courtney Diamond, cjd2195<br>
  - Hyun Jin Jung, hj2660<br>
  - Jesus Luevano, jl5934<br>
  - Kayla Schiffer-Kane, khs2138<br>
  - Haley Zylberberg, hmz2105<br> 
  &nbsp;

## Motivation
Increasing transportation costs, congested streets, and subway delays across New York City are pressuring residents to find cheaper and faster means of navigating the Big Apple. CitiBikes have had an impact in increasing access to biking as a viable alternative to other means of transportation. There is an added health benefit to the physical activity of biking. Bike usage also confers health related benefits on air quality. The utilization of CitiBikes, however, is dependent on factors such as availability of bike stations, bike lanes, and the cost of bike rides and membership. 

We, as young professionals/students in the city, want to know if turning to CitiBike is a viable alternative. We also want to explore if there is disproportionate availability and utilization of CitiBikes across neighborhoods with varied social deprivation index that can exacerbate disparities in health status. To that end, we will explore CitiBike usage, aiming to understand usage patterns related to location within NYC, and its relation to social deprivation index, air quality, and health outcomes. &nbsp;


