---
title: "<span style='color: blue;'>Project Report</span>"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
css: styles.css
---

=======
  &nbsp;

***

## <span style='color: blue;'>From Pedals to Patterns: A P8105 Citibike Data Analysis</span>

## <span style='color: blue;'>Team Members</span>
  - Laura O'Carroll, lgo2107<br>
  - Courtney Diamond, cjd2195<br>
  - Hyun Jin Jung, hj2660<br>
  - Jesus Luevano, jl5934<br>
  - Kayla Schiffer-Kane, khs2138<br>
  - Haley Zylberberg, hmz2105<br> 

## <span style='color: blue;'>Motivation</span>

Increasing transportation costs, congested streets, and subway delays across New York City are pressuring residents to find cheaper and faster means of navigating the Big Apple. The introduction of [Citibike](https://citibikenyc.com/) has had an impact in increasing access to biking as an alternative means of transportation. Biking also has the added benefit of promoting health! However, a critical question emerges: Does every NYer enjoy equitable access to these bikes and the health advantages they confer?

As public health students grappling with the daily commute in the dynamic landscape of NYC, we are driven by a collective curiosity to determine the viability and equity of turning to CitiBike as a transportation alternative. Our exploration is multi-faceted, aiming to delve into the intricacies of CitiBike usage:

  * Geographical Utilization: We seek to unravel the patterns of CitiBike usage throughout the diverse neighborhoods of NYC. Understanding where and when these bikes are utilized is integral to discerning the impact on urban mobility.
  * User Demographics: A crucial part of our inquiry involves identifying the demographics of CitiBike users. 
  * Neighborhood Disparities: We aim to investigate if there is an uneven distribution of CitiBikes across neighborhoods, particularly focusing on areas characterized by higher levels of social deprivation. Addressing this aspect is pivotal in gauging the accessibility and inclusiveness of the CitiBike system.
  * Health Implications: Beyond transportation, we aim to examine whether disproportionate access to CitiBikes might contribute to health disparities among NYers. This involves exploring associations between CitiBike availability, social deprivation indices, air quality, and being overweight.

By delving into these dimensions, we aim to understand how CitiBike intersects with public health and urban life in NYC.

  &nbsp;

***

## <span style='color: blue;'>Related Work</span>

After spending time on the airbnb data sources in class, we were particularly interested in exploring an NYC related source of data. As we are public health students and our group also includes healthcare professionals our focus naturally gravitated toward a dataset with potential relevance to the health of NYers. While we evaluated several potential data sources, we were collectively interested in Citibike usage data, as we recognized its potential to offer valuable insights into the intersection of transportation patterns and public health in NYC.

  &nbsp;

***

## <span style='color: blue;'>Initial Questions</span>

Initially, our focus revolved around the customer usability of Citibike, with a specific emphasis on time-related factors. We posed questions aimed at understanding user utilization patterns, specifically the ratio of recurrent subscribers to one-time customers and examining trends that might suggest tourist usage, especially around holidays. Additionally, we sought to understand the temporal variations in this ratio, both throughout the day and across different seasons. We inquired about potential discrepancies in ride duration between subscribers and one-time customers and how these durations might fluctuate based on the time of day, season, and varying weather conditions. 

While we still wanted to explore Citibike usage, throughout the evolution of our project, we decided to shift more towards neighborhood specific usage. This fit better with our desire to explore health and equity and introduced a more nuanced layer to our data exploration. 

***

## <span style='color: blue;'>Data</span>

Data: Source, scraping method, cleaning, etc.

  &nbsp;

***

## <span style='color: blue;'>Exploratory Analysis</span>
Exploratory analysis: Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.

  &nbsp;

***

## <span style='color: blue;'>Additional Analysis</span>
Additional analysis: If you undertake formal statistical analyses, describe these in detail

  &nbsp;

***

## <span style='color: blue;'>Discussion</span>
Discussion: What were your findings? Are they what you expect? What insights into the data can you make?
