---
title: Visualizing AQI, SDI, and Overweight Data at Citibike Stations Across Boroughs
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(here)
library(shiny)
library(shinyjs)
library(RColorBrewer)

knitr::opts_chunk$set(message = FALSE,
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

library(ggridges)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r datasets, include = FALSE}
# setwd("./exploratory_dashboard")

start_stations_manhattan = read_csv("data/start_stations_Manhattan.csv")
start_stations_brooklyn = read_csv("data/start_stations_Brooklyn.csv")
start_stations_queens = read_csv("data/start_stations_Queens.csv")
start_stations_bronx = read_csv("data/start_stations_Bronx.csv")

start_stations = rbind(start_stations_manhattan, start_stations_brooklyn, start_stations_queens, start_stations_bronx)

end_stations_manhattan = read_csv("data/end_stations_Manhattan.csv")
end_stations_brooklyn = read_csv("data/end_stations_Brooklyn.csv")
end_stations_queens = read_csv("data/end_stations_Queens.csv")
end_stations_bronx = read_csv("data/end_stations_Bronx.csv")
end_stations = rbind(end_stations_manhattan, end_stations_brooklyn, end_stations_queens, end_stations_bronx)

start_end_manhattan = read_csv("data/start_end_Manhattan.csv")
start_end_brooklyn = read_csv("data/start_end_Brooklyn.csv")
start_end_queens = read_csv("data/start_end_Queens.csv")
start_end_bronx = read_csv("data/start_end_Bronx.csv")

```

Column {.sidebar}
-----------------------------------------------------------------------

This dashboard can help you explore Citibike ridership data for September 2019 by borough. The top left GeoMap also allows you to investigate specific health metrics for each Citibike station.


```{r inputs, echo = FALSE}

borough = c("Manhattan", "Brooklyn", "Bronx", "Queens")


selectInput(
  inputId = "borough_choice",
  label = h3("Select a Borough"),
  choices = borough,
  selected = "Manhattan"
)

hr()

extra_variable = c("AQI", "SDI", "Percent Overweight")

radioButtons(
  inputId = "health_var",
  label = h3("Select a Health Metric (for GeoMap only)"),
  choices = extra_variable,
  selected = "AQI"
)

```


Row {data-height = 350}
-----------------------------------------------------------------------

### Health Metrics by Citibike Station Location

```{r, echo = FALSE}

renderPlotly({

borough_here = input$borough_choice

if (input$health_var == "AQI") {
  
  start_stations |>
  filter(start_borough == borough_here) |> 
  distinct(start_station_name, .keep_all = TRUE) |> 
  select(start_station_name, start_zipcode, start_station_latitude, start_station_longitude, start_uhf34_neighborhood, start_borough, start_sdi_score, start_percent_overweight, start_aq) |> 
  mutate(text_label = str_c("Station: ", start_station_name, "\nAQI: ", start_aq, "\nPercent Overweight: ", start_percent_overweight, "\nSDI: ", start_sdi_score)) |> 
  plot_ly(x = ~start_station_longitude, y = ~start_station_latitude, type = "scatter", mode = "markers", color = ~start_aq, text = ~text_label, alpha = 0.5)
  
}


else if (input$health_var == "Percent Overweight") {
  start_stations |>
  filter(start_borough == borough_here) |> 
  distinct(start_station_name, .keep_all = TRUE) |> 
  select(start_station_name, start_zipcode, start_station_latitude, start_station_longitude, start_uhf34_neighborhood, start_borough, start_sdi_score, start_percent_overweight, start_aq) |> 
  mutate(text_label = str_c("Station: ", start_station_name, "\nAQI: ", start_aq, "\nPercent Overweight: ", start_percent_overweight, "\nSDI: ", start_sdi_score)) |> 
  plot_ly(x = ~start_station_longitude, y = ~start_station_latitude, type = "scatter", mode = "markers", color = ~start_percent_overweight, text = ~text_label, alpha = 0.5)
}

else if (input$health_var == "SDI") {
  
  start_stations |>
  filter(start_borough == borough_here) |> 
  distinct(start_station_name, .keep_all = TRUE) |> 
  select(start_station_name, start_zipcode, start_station_latitude, start_station_longitude, start_uhf34_neighborhood, start_borough, start_sdi_score, start_percent_overweight, start_aq) |> 
  mutate(text_label = str_c("Station: ", start_station_name, "\nAQI: ", start_aq, "\nPercent Overweight: ", start_percent_overweight, "\nSDI: ", start_sdi_score)) |> 
  plot_ly(x = ~start_station_longitude, y = ~start_station_latitude, type = "scatter", mode = "markers", color = ~start_sdi_score, text = ~text_label, alpha = 0.5)
  
}
  
})

```


### Sankey Flowchart of Intra-Borough Rides

```{r, echo = FALSE}


renderPlotly({

if (input$borough_choice == "Manhattan") {
  
sankey_man =
  start_end_manhattan |>  
  mutate(node1 = case_match(start_uhf34_neighborhood,
                           "Union Square, Lower Manhattan (Start)" ~ 0,
                           "Upper West Side (Start)" ~ 1, 
                           "Chelsea Village (Start)" ~ 2,
                           "Upper East Side Gramercy (Start)" ~ 3,
                           "East Harlem (Start)" ~ 4,
                           "Central Harlem Morningside Heights (Start)" ~ 5,
                           "Washington Heights Inwood (Start)" ~ 6),
         node2 = case_match(end_uhf34_neighborhood,
                           "Union Square, Lower Manhattan (End)" ~ 7,
                           "Upper West Side (End)" ~ 8, 
                           "Chelsea Village (End)" ~ 9,
                           "Upper East Side Gramercy (End)" ~ 10,
                           "East Harlem (End)" ~ 11,
                           "Central Harlem Morningside Heights (End)" ~ 12,
                           "Washington Heights Inwood (End)" ~ 13))

 
sankey_plot_man = 
  plot_ly(type = "sankey",
          orientation = "h",
          node = list(
                label = c("Union Square, Lower Manhattan (Start)", "Upper West Side (Start)", "Chelsea Village (Start)", "Upper East Side Gramercy (Start)", "East Harlem (Start)", "Central Harlem Morningside Heights (Start)", "Washington Heights Inwood (Start)", "Union Square, Lower Manhattan (End)", "Upper West Side (End)", "Chelsea Village (End)", "Upper East Side Gramercy (End)", "East Harlem (End)", "Central Harlem Morningside Heights (End)", "Washington Heights Inwood (End)"),
                color = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F", "#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F"),
                pad = 15,
                thickness = 20,
                line = list(color = "black",width = 0.5)),
          link = list(
                source = sankey_man |>  pull(node1),
                target = sankey_man |>  pull(node2),
                value =  sankey_man |>  pull(n)))

sankey_plot_man |> 
  layout(
    title = "Citibike Trips Completed in Manhattan, by Neighborhood",
    font = list(size = 10))  
  
}


else if (input$borough_choice == "Brooklyn") {
  
sankey_bklyn =
  start_end_brooklyn |>
  mutate(node1 = case_match(start_uhf34_neighborhood,
                            "Downtown Heights Slope (Start)" ~ 0,
                            "Williamsburg Bushwick (Start)" ~ 1, 
                            "Greenpoint (Start)" ~ 2,
                            "East New York (Start)" ~ 3,
                            "Bedford Stuyvesant Crown Heights (Start)" ~ 4,
                            "East Flatbush Flatbush (Start)" ~ 5,
                            "Coney Island Sheepshead Bay (Start)" ~ 6,
                            "Bensonhurst Bay Ridge (Start)" ~ 7,
                            "Sunset Park (Start)" ~ 8),
         node2 = case_match(end_uhf34_neighborhood,
                           "Downtown Heights Slope (End)" ~ 9,
                            "Williamsburg Bushwick (End)" ~ 10, 
                            "Greenpoint (End)" ~ 11,
                            "East New York (End)" ~ 12,
                            "Bedford Stuyvesant Crown Heights (End)" ~ 13,
                            "East Flatbush Flatbush (End)" ~ 14,
                            "Coney Island Sheepshead Bay (End)" ~ 15,
                            "Bensonhurst Bay Ridge (End)" ~ 16,
                            "Sunset Park (End)" ~ 17))

 
sankey_plot_bklyn = 
  plot_ly(type = "sankey",
          orientation = "h",
          node = list(
                label = c("Downtown Heights Slope (Start)", "Williamsburg Bushwick (Start)", "Greenpoint (Start)", "East New York (Start)", "Bedford Stuyvesant Crown Heights (Start)", "East Flatbush Flatbush (Start)", "Coney Island Sheepshead Bay (Start)", "Bensonhurst Bay Ridge (Start)", "Sunset Park (Start)", "Downtown Heights Slope (End)", "Williamsburg Bushwick (End)",  "Greenpoint (End)", "East New York (End)", "Bedford Stuyvesant Crown Heights (End)", "East Flatbush Flatbush (End)", "Coney Island Sheepshead Bay (End)", "Bensonhurst Bay Ridge (End)", "Sunset Park (End)"),
                color = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00", "#CAB2D6", "#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00", "#CAB2D6"),
                pad = 15,
                thickness = 20,
                line = list(color = "black", width = 0.5)),
          link = list(
                source = sankey_bklyn |>  pull(node1),
                target = sankey_bklyn |>  pull(node2),
                value =  sankey_bklyn |>  pull(n)))

sankey_plot_bklyn |> 
  layout(
    title = "Citibike Trips Completed in Brooklyn, by Neighborhood",
    font = list(size = 10))
}

else if (input$borough_choice == "Queens") {
  
sankey_qns = 
  start_end_queens |>
  mutate(node1 = case_match(start_uhf34_neighborhood,
                            "Long Island City Astoria (Start)" ~ 0,
                            "West Queens (Start)" ~ 1,
                            "Ridgewood Forest Hills (Start)" ~ 2),
         node2 = case_match(end_uhf34_neighborhood,
                            "Long Island City Astoria (End)" ~ 3,
                            "West Queens (End)" ~ 4,
                            "Ridgewood Forest Hills (End)" ~ 5))
 
sankey_plot_qns = 
  plot_ly(type = "sankey",
          orientation = "h",
          node = list(
                label = c("Long Island City Astoria (Start)", "West Queens (Start)", "Ridgewood Forest Hills (Start)", "Long Island City Astoria (End)", "West Queens (End)", "Ridgewood Forest Hills (End)"),
                color = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#A6CEE3", "#1F78B4", "#B2DF8A"),
                pad = 15,
                thickness = 20,
                line = list(color = "black", width = 0.5)),
          link = list(
                source = sankey_qns |>  pull(node1),
                target = sankey_qns |>  pull(node2),
                value =  sankey_qns |>  pull(n)))

sankey_plot_qns |> 
  layout(
    title = "Citibike Trips Completed in Queens, by Neighborhood",
    font = list(size = 10))

}

else if (input$borough_choice == "Bronx") {

sankey_bx = 
  start_end_bronx |>
  mutate(node1 = case_match(start_uhf34_neighborhood,
                            "Kingsbridge Riverdale (Start)" ~ 0),
         node2 = case_match(end_uhf34_neighborhood,
                            "Kingsbridge Riverdale (End)" ~ 1))
sankey_bx
 
sankey_plot_bx = 
  plot_ly(type = "sankey",
          orientation = "h",
          node = list(
                label = c("Kingsbridge Riverdale (Start)", "Kingsbridge Riverdale (End)"),
                color = c("#A6CEE3","#A6CEE3"),
                pad = 15,
                thickness = 20,
                line = list(color = "black", width = 0.5)),
          link = list(
                source = sankey_bx |>  pull(node1),
                target = sankey_bx |>  pull(node2),
                value =  sankey_bx |>  pull(n)))

sankey_plot_bx |> 
  layout(
    title = "Citibike Trips Completed in the Bronx, by Neighborhood",
    font = list(size = 10))
}
  
})
```



Row {.tabset .tabset-fade} 
-----------------------------------------------------------------------

### Rides originating, by Citibike station
```{r, echo = FALSE}

renderPlotly({

borough_here = input$borough_choice

if (input$health_var == "AQI") {
  
  start_stations |>
  filter(start_borough == borough_here) |> 
  select(start_station_name, start_uhf34_neighborhood, start_borough, start_station_count, start_sdi_score, start_percent_overweight, start_aq) |> 
  mutate(start_station_name = fct_reorder(start_station_name, start_station_count)) |> 
  mutate(start_station_count = as.numeric(start_station_count)) |> 
  plot_ly(x = ~start_station_name, y = ~start_station_count, type = "bar", color = ~start_uhf34_neighborhood)
  
}


else if (input$health_var == "Percent Overweight"){
  
  start_stations |>
  filter(start_borough == borough_here) |> 
  select(start_station_name, start_uhf34_neighborhood, start_borough, start_station_count, start_sdi_score, start_percent_overweight, start_aq) |> 
  mutate(start_station_name = fct_reorder(start_station_name, start_station_count)) |> 
  mutate(start_station_count = as.numeric(start_station_count)) |> 
  plot_ly(x = ~start_station_name, y = ~start_station_count, type = "bar", color = ~start_uhf34_neighborhood)
  
}

else if (input$health_var == "SDI") {
  
  start_stations |>
  filter(start_borough == borough_here) |> 
  select(start_station_name, start_uhf34_neighborhood, start_borough, start_station_count, start_sdi_score, start_percent_overweight, start_aq) |> 
  mutate(start_station_name = fct_reorder(start_station_name, start_station_count)) |> 
  mutate(start_station_count = as.numeric(start_station_count)) |> 
  plot_ly(x = ~start_station_name, y = ~start_station_count, type = "bar", color = ~start_uhf34_neighborhood)

}

})
```

### Rides terminating, by Citibike station

```{r, echo = FALSE}
renderPlotly({

borough_here = input$borough_choice

if (input$health_var == "AQI") {
  
  end_stations |>
  filter(end_borough == borough_here) |> 
  select(end_station_name, end_uhf34_neighborhood, end_borough, end_station_count, end_sdi_score, end_percent_overweight, end_aq) |> 
  mutate(end_station_name = fct_reorder(end_station_name, end_station_count)) |> 
  mutate(end_station_count = as.numeric(end_station_count)) |>
  plot_ly(x = ~end_station_name, y = ~end_station_count, type = "bar", color = ~end_uhf34_neighborhood)
  
}


else if (input$health_var == "Percent Overweight"){
  
  end_stations |>
  filter(end_borough == borough_here) |> 
  select(end_station_name, end_uhf34_neighborhood, end_borough, end_station_count, end_sdi_score, end_percent_overweight, end_aq) |> 
  mutate(end_station_name = fct_reorder(end_station_name, end_station_count)) |> 
  mutate(end_station_count = as.numeric(end_station_count)) |>
  plot_ly(x = ~end_station_name, y = ~end_station_count, type = "bar", color = ~end_uhf34_neighborhood)
  
}

else if (input$health_var == "SDI") {

  end_stations |>
  filter(end_borough == borough_here) |> 
  select(end_station_name, end_uhf34_neighborhood, end_borough, end_station_count, end_sdi_score, end_percent_overweight, end_aq) |> 
  mutate(end_station_name = fct_reorder(end_station_name, end_station_count)) |> 
  mutate(end_station_count = as.numeric(end_station_count)) |>
  plot_ly(x = ~end_station_name, y = ~end_station_count, type = "bar", color = ~end_uhf34_neighborhood)
  
}

})
```



